services:
  - type: web
    name: rag-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:5000 rag_bot:app
    plan: free
    envVars:
      - key: ENV_VAR_NAME
        value: value
